In [1]:
import numpy as np
import pandas as pd

In [4]:
np.random.randint(1 , 65 , 8)

array([ 2, 50, 37,  8,  1, 26, 38, 58])

In [5]:
np.zeros((4 , ))

array([0., 0., 0., 0.])

In [7]:
np.empty((4 , 2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 5.88926250e-321],
       [6.79038653e-313, 8.70018274e-313]])

In [14]:
from sklearn.model_selection import KFold    

In [ ]:
KFold()